name: request_luxo_app
description: "Luxo requests - A Flutter application for automating service request submissions for Luxo Place residents."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Data Persistence
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Image Handling
  image_picker: ^1.1.2

  # Web Automation
  flutter_inappwebview: ^6.0.0

  # HTTP Requests (for scraping if needed)
  http: ^1.5.0

  # File handling
  path_provider: ^2.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code Generation for Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # You can add assets here in the future if needed
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Example of how to add custom fonts if needed
  # fonts:
  #   - family: LuxoFont
  #     fonts:
  #       - asset: assets/fonts/LuxoFont-Regular.ttf
  #       - asset: assets/fonts/LuxoFont-Bold.ttf
  #         weight: 700